import '!file?name=components/polymer/[name].[ext]!../bower_components/polymer/layout.html'
import '!file?name=components/polymer/[name].[ext]!../bower_components/polymer/polymer.html'
import '!file?name=components/polymer/[name].[ext]!../bower_components/polymer/polymer.js'

import '!file?name=components/core-toolbar/[name].[ext]!../bower_components/core-toolbar/core-toolbar.html'
import '!file?name=components/core-toolbar/[name].[ext]!../bower_components/core-toolbar/core-toolbar.css'
import '!file?name=components/core-header-panel/[name].[ext]!../bower_components/core-header-panel/core-header-panel.css'
import '!file?name=components/core-header-panel/[name].[ext]!../bower_components/core-header-panel/core-header-panel.html'
import '!file?name=components/core-icons/[name].[ext]!../bower_components/core-icons/core-icons.html'
import '!file?name=components/core-selector/[name].[ext]!../bower_components/core-selector/core-selector.html'
import '!file?name=components/core-resizable/[name].[ext]!../bower_components/core-resizable/core-resizable.html'
import '!file?name=components/core-selection/[name].[ext]!../bower_components/core-selection/core-selection.html'
import '!file?name=components/core-icon/[name].[ext]!../bower_components/core-icon/core-icon.html'
import '!file?name=components/core-icon/[name].[ext]!../bower_components/core-icon/core-icon.css'
import '!file?name=components/core-iconset/[name].[ext]!../bower_components/core-iconset/core-iconset.html'
import '!file?name=components/core-iconset-svg/[name].[ext]!../bower_components/core-iconset-svg/core-iconset-svg.html'
import '!file?name=components/core-meta/[name].[ext]!../bower_components/core-meta/core-meta.html'
import '!file?name=components/core-focusable/[name].[ext]!../bower_components/core-focusable/core-focusable.html'
import '!file?name=components/core-focusable/[name].[ext]!../bower_components/core-focusable/core-focusable.js'
import '!file?name=components/core-focusable/[name].[ext]!../bower_components/core-focusable/polymer-mixin.js'

import '!file?name=components/paper-icon-button/[name].[ext]!../bower_components/paper-icon-button/paper-icon-button.html'
import '!file?name=components/paper-tabs/[name].[ext]!../bower_components/paper-tabs/paper-tabs.html'
import '!file?name=components/paper-tabs/[name].[ext]!../bower_components/paper-tabs/paper-tabs.css'
import '!file?name=components/paper-tabs/[name].[ext]!../bower_components/paper-tabs/paper-tab.html'
import '!file?name=components/paper-tabs/[name].[ext]!../bower_components/paper-tabs/paper-tab.css'
import '!file?name=components/paper-button/[name].[ext]!../bower_components/paper-button/paper-button-base.html'
import '!file?name=components/paper-ripple/[name].[ext]!../bower_components/paper-ripple/paper-ripple.html'
import '!file?name=components/font-roboto/[name].[ext]!../bower_components/font-roboto/roboto.html'

import './scss/bootstrap.scss'
import './components/app-main/app-main.js'
import '../bower_components/webcomponentsjs/webcomponents.js'
